spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/jwt-demo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
logging:
  level:
    "liquibase" : info