spring:
  application:
    name: jwt-auth
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/jwt-demo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
logging:
  level:
    "liquibase": INFO
    root: WARN
    pro.paullezin.jwtdemo: INFO