spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/jwt-demo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true